name: recipe_firebase_mealdb_code
description: Recipe app with Firebase Auth, Firestore saved recipes, and TheMealDB API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  http: ^1.2.2
  share_plus: ^10.1.4
  url_launcher: ^6.3.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
