// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAipg4GxDy-V_xYRhBzKHC0JiM9bQrOuk4',
    appId: '1:98508439582:web:2804a1243980b0bda16e0f',
    messagingSenderId: '98508439582',
    projectId: 'recipe-app-flutter-404aa',
    authDomain: 'recipe-app-flutter-404aa.firebaseapp.com',
    storageBucket: 'recipe-app-flutter-404aa.firebasestorage.app',
    measurementId: 'G-CWB3G8ZGLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK3ea1LZE1v6NviMTrHMH7wnCWTLnJ0EA',
    appId: '1:98508439582:android:db928c13d17e6d29a16e0f',
    messagingSenderId: '98508439582',
    projectId: 'recipe-app-flutter-404aa',
    storageBucket: 'recipe-app-flutter-404aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjY3jdYLGUj44zankg_i0Le55wUH7Cg-A',
    appId: '1:98508439582:ios:f185e43f6c608fa4a16e0f',
    messagingSenderId: '98508439582',
    projectId: 'recipe-app-flutter-404aa',
    storageBucket: 'recipe-app-flutter-404aa.firebasestorage.app',
    iosBundleId: 'com.recipe.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjY3jdYLGUj44zankg_i0Le55wUH7Cg-A',
    appId: '1:98508439582:ios:f185e43f6c608fa4a16e0f',
    messagingSenderId: '98508439582',
    projectId: 'recipe-app-flutter-404aa',
    storageBucket: 'recipe-app-flutter-404aa.firebasestorage.app',
    iosBundleId: 'com.recipe.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAipg4GxDy-V_xYRhBzKHC0JiM9bQrOuk4',
    appId: '1:98508439582:web:00c124e1f77bd0daa16e0f',
    messagingSenderId: '98508439582',
    projectId: 'recipe-app-flutter-404aa',
    authDomain: 'recipe-app-flutter-404aa.firebaseapp.com',
    storageBucket: 'recipe-app-flutter-404aa.firebasestorage.app',
    measurementId: 'G-92S57G3JKJ',
  );
}
